openapi: 3.0.3
info:
  title: Lychee
  description: This describes all the API endpoint available.
  version: 1.0.0
servers:
  - url: 'http://lychee.test/api'
  - url: 'https://lychee.test/api'
paths:
  /albums:
    get:
      summary: List albums
      description: Returns a list of all albums
      operationId: albumIndex
      security:
        - cookieAuth: [ ]
      tags:
        - "Albums"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: Albums Response Object
                properties:
                  albums:
                    type: array
                    description: A collection of albums
                    items:
                      $ref: '#/components/schemas/Album'
                  shared_albums:
                    type: array
                    description: A collection of shared albums
                    items:
                      $ref: '#/components/schemas/Album'
                  smart_albums:
                    type: object
                    description: Smart albums
                    properties:
                      unsorted:
                        $ref: '#/components/schemas/SmartAlbum'
                      public:
                        $ref: '#/components/schemas/SmartAlbum'
                      starred:
                        $ref: '#/components/schemas/SmartAlbum'
                      recent:
                        $ref: '#/components/schemas/SmartAlbum'
  /albums/{albumId}:
    get:
      summary: Show album
      description: Returns an album
      operationId: albumShow
      security:
        - cookieAuth: [ ]
      tags:
        - "Albums"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: Albums Response Object
                properties:
                  data:
                    $ref: '#/components/schemas/Album'
  /users:
    get:
      summary: List of Users
      description: Returns a list of all users
      operationId: userIndex
      security:
        - cookieAuth: [ ]
      tags:
        - "Users"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: A collection of users
                items:
                  description: A User
                  type: object
                  required:
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    upload:
                      type: integer
                    lock:
                      type: integer
                    type:
                      type: string
    post:
      summary: User Store
      description: Create a new user
      operationId: userCreate
      security:
        - cookieAuth: [ ]
      tags:
        - "Users"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: A User fillable fields
              required:
                - username
                - password
                - lock
                - upload
              properties:
                username:
                  description: Username
                  type: string
                  example: John
                password:
                  description: Password
                  type: string
                  example: User's password
                lock:
                  type: string
                  enum:
                    - '0'
                    - '1'
                  example: '1'
                upload:
                  type: string
                  enum:
                    - '0'
                    - '1'
                  example: '1'
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                description: Return value
                enum:
                  - 'true'
                  - 'false'
  /users/{user}:
    put:
      summary: Update a User
      description: Update Users fillable
      operationId: userUpdate
      security:
        - cookieAuth: [ ]
      tags:
        - "Users"
      requestBody:
        content:
          text/html:
            schema:
              type: object
              description: A User fillable fields
              required:
                - username
                - password
                - lock
                - upload
              properties:
                username:
                  description: Username
                  type: string
                  example: John
                password:
                  description: Password
                  type: string
                  example: User's password
                lock:
                  type: string
                  enum:
                    - '0'
                    - '1'
                  example: '1'
                upload:
                  type: string
                  enum:
                    - '0'
                    - '1'
                  example: '1'
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                description: Return value
                enum:
                  - 'true'
                  - 'false'
    delete:
      summary: Delete a user
      description: Hard deleting the provider user
      operationId: userDestroy
      security:
        - cookieAuth: [ ]
      tags:
        - "Users"
      responses:
        '204':
          description: OK
components:
  schemas:
    SmartAlbum:
      type: object
      description: Smart Album structure content
      required:
        - num
        - thumbs
        - thumbs2x
        - types
      properties:
        num:
          type: integer
          nullable: true
          format: int64
          description: Number of photo in the SmartAlbum.
          default: null
          example: 1134
        thumbs:
          type: array
          description: All photo's thumbs links
          items:
            type: string
            description: Thumbs relative link
            default: null
            nullable: true
            example: uploads/thumb/53598fc2ad6d9527df28ae5eec94509d.jpeg
        thumbs2x:
          type: array
          description: All photo's thumbs @2x links
          items:
            type: string
            description: Thumbs 2x relative link
            default: null
            nullable: true
            example: uploads/thumb/53598fc2ad6d9527df28ae5eec94509d@2x.jpeg
        types:
          type: array
          description: All album's photo's types
          items:
            type: string
            description: Mime Type
            default: null
            nullable: true
            example: image/jpeg
    Album:
      type: object
      description: Album structure content
      required:
        - id
        - title
        - photos
      properties:
        id:
          type: integer
          format: int64
          description: Album Identifier.
          example: 1134
        title:
          type: string
          description: The album title
          example: My Trip In Arizona.
        public:
          type: boolean
          description: Whether the album is public or not.
          default: false
        full_photo:
          type: boolean
          description: Whether the album's photo can be seen at full resolution.
          default: false
        visible:
          type: boolean
          description: Whether the album is visible or not.
          default: false
        parent_id:
          type: integer
          nullable: true
          format: int64
          description: Album's Parent Identifier.
          default: null
          example: 1134
        description:
          type: string
          description: The album description
          nullable: true
          example: My Trip In Arizona.
          default: null
        downloadable:
          type: boolean
          description: Whether the album can be downloaded or not.
          default: false
        share_button_visible:
          type: boolean
          description: Whether we can display the share button or not.
          default: false
        sysdate:
          type: integer
          format: int64
          description: The album creation date
          example: 1597942667
        min_takestamp:
          type: integer
          nullable: true
          format: int64
          description: The oldest photo's date in the album
          example: 1597942667
          default: null
        max_takestamp:
          type: integer
          nullable: true
          format: int64
          description: The most recent photo's date in the album
          example: 1597942667
          default: null
        password:
          type: boolean
          description: Whether the album is password protected or not
          example: false
          default: false
        license:
          type: string
          description: The album's license
          example: CC-BY-NC-SA-1.0
          default: none
        thumbs:
          type: array
          description: All photo's thumbs links
          items:
            type: string
            description: Thumbs relative link
            default: null
            nullable: true
            example: uploads/thumb/53598fc2ad6d9527df28ae5eec94509d.jpeg
        thumbs2x:
          type: array
          description: All photo's thumbs @2x links
          items:
            type: string
            description: Thumbs 2x relative link
            default: null
            nullable: true
            example: uploads/thumb/53598fc2ad6d9527df28ae5eec94509d@2x.jpeg
        types:
          type: array
          description: All album's photo's types
          items:
            type: string
            description: Mime Type
            default: null
            nullable: true
            example: image/jpeg
        children:
          type: array
          description: Album's photos
          items:
              type: integer
              format: int64
              description: Album Identifier.
              example: 1134
        photos:
          type: array
          description: Children albums
          items:
            $ref: '#/components/schemas/Photo'
    Photo:
      type: object
      description: Photo structure content
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
          description: Photo Identifier.
          example: 1134
        title:
          type: string
          description: The photo title
          example: My Trip In Arizona.
        tags:
          type: string
          description: Tags associated to the photo.
          default: null
        star:
          type: boolean
          description: Whether the photo is starred.
          default: false
        album:
          type: integer
          format: int64
          description: Album identifier.
          example: 1134
        width:
          type: integer
          nullable: true
          format: int64
          description: Photo's width in pixels.
          example: 1134
        height:
          type: integer
          nullable: true
          format: int64
          description: Photo's height in pixels.
          example: 1134
        description:
          type: string
          description: The album description
          nullable: true
          example: My Trip In Arizona.
          default: null
        type:
          type: string
          description: Photo's mime type.
          example: image/jpeg
        iso:
          type: string
          description: ISO in Photo Metadata.
          example: 125
        aperture:
          type: string
          description: Aperture in Photo Metadata.
          example: F/2.8
        make:
          type: string
          description: Camera's make in Photo Metadata
          example: Canon
        model:
          type: string
          description: Camera's model in Photo Metadata.
          example: EOS R5
        shutter:
          type: string
          description: Shutter Speed in Photo Metadata.
          example: 1/250 s
        focal:
          type: string
          description: Focal length in Photo Metadata.
          example: 35 mm
        size:
          type: string
          description: Human readable file size.
          example: 1.6 MB
        lens:
          type: string
          description: Lens in Photo Metadata.
          example: OLYMPUS M.40-150mm F2.8
        latitude:
          type: string
          description: Latitude in Photo Metadata.
          nullable: true
          default: null
        longitude:
          type: string
          description: Longitude in Photo Metadata.
          nullable: true
          default: null
        altitude:
          type: string
          description: Altitude in Photo Metadata.
          nullable: true
          default: null
        imgDirection:
          type: string
          description: Image Direction in Photo Metadata.
          nullable: true
          default: null
        location:
          type: string
          description: Location in Photo Metadata.
          nullable: true
          default: null
        livePhotoContentID:
          type: string
          description: livePhotoContentID.
          nullable: true
          default: null
        sysdate:
          type: integer
          format: int64
          description: The photo creation date in the system
          example: 1597942667
        takedate:
          type: integer
          format: int64
          description: The photo capture date
          example: 1597942667
        license:
          type: string
          description: The photo's license
          example: CC-BY-NC-SA-1.0
          default: none
        thumbUrl:
          type: string
          description: Thumbs relative link
          default: null
          nullable: true
          example: uploads/thumb/53598fc2ad6d9527df28ae5eec94509d.jpeg
        thumbs2x:
          type: string
          description: Thumbs 2x relative link
          default: null
          nullable: true
          example: uploads/thumb/53598fc2ad6d9527df28ae5eec94509d@2x.jpeg
        medium:
          type: string
          description: Medium Size relative link
          default: null
          nullable: true
          example: uploads/medium/53598fc2ad6d9527df28ae5eec94509d.jpeg
        medium_dim:
          type: string
          description: Medium Size dimensions
          default: null
          nullable: true
          example: 1600x1080
        medium2x:
          type: string
          description: Medium Size 2x relative link
          default: null
          nullable: true
          example: uploads/medium/53598fc2ad6d9527df28ae5eec94509d@2x.jpeg
        medium2x_dim:
          type: string
          description: Medium Size 2x dimensions
          default: null
          nullable: true
          example: 3200x2160
        small:
          type: string
          description: Small Size relative link
          default: null
          nullable: true
          example: uploads/small/53598fc2ad6d9527df28ae5eec94509d.jpeg
        small_dim:
          type: string
          description: Small Size dimensions
          default: null
          nullable: true
          example: 533x360
        small2x:
          type: string
          description: Small Size 2x relative link
          default: null
          nullable: true
          example: uploads/small/53598fc2ad6d9527df28ae5eec94509d@2x.jpeg
        small2x_dim:
          type: string
          description: Small Size 2x dimensions
          default: null
          nullable: true
          example: 1066x720
        url:
          type: string
          description: Full size relative link
          default: null
          nullable: true
          example: uploads/big/53598fc2ad6d9527df28ae5eec94509d@2x.jpeg
        livePhotoUrl:
          type: string
          description: livePhotoUrl
          default: null
          nullable: true
  securitySchemes:
    cookieAuth: # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: lychee_session  # cookie name
