name: Code Analysis

on:
    push: null
    pull_request:
        branches:
            - main

jobs:
    code_standard:
        name: Coding Standard
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress
            -   run: vendor/bin/ecs check --ansi